[package]
name = "EdDSA-keygen"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22"
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = { version = "0.8", features = ["std"] }
